"Leave Room feature updated and tested"
CSC207-2023Y-UofT/course-project-larklink pull request #70
Opened 2023-07-21 01:15 UTC by margaretpell

I also wrote RoomDB and RoomView's leave room part in order to run the code and I inserted users in specific room in RoomDBAccess for testing which can be deleted after merging.

2023-07-24 14:54 UTC, aldew5 approved these changes
capitalize ID (convention we've followed so far) and not sure why we have hardcoded users in createRooms

2023-07-24 14:54 UTC, aldew5 commented on src/main/java/leaveRoom/RoomDBAccess.java
> +    }
is this just for testing? If so delete

2023-07-24 14:54 UTC, aldew5 commented on src/main/java/leaveRoom/RoomDBRequestModel.java
> +    private String roomId;
roomID

2023-07-24 14:54 UTC, aldew5 commented on src/main/java/leaveRoom/RoomView.java
> +    private String roomId;
caps on ID

2023-07-24 14:57 UTC, weihan1 approved these changes

2023-07-24 15:42 UTC, vincecloutier requested changes

2023-07-24 15:42 UTC, vincecloutier commented on src/main/java/leaveRoom/LeaveRoomPresenter.java
what if we had prepareJoinOrHostView and something prepareFailedToLeaveRoomView, this would allow us to get right of leave room response model and do something similar to UserPresenter ?

2023-07-24 15:42 UTC, vincecloutier commented on src/main/java/leaveRoom/LeaveRoomOutputBoundary.java
see note from LeaveRoomPresenter

2023-07-24 15:42 UTC, vincecloutier commented on src/main/java/leaveRoom/LeaveRoomResponseModel.java
see note from LeaveRoomPresenter

2023-07-24 15:43 UTC, vincecloutier commented on src/main/java/leaveRoom/LeaveRoomPresenter.java
if I'm wrong about this just let me know and I'll resolve this - I just think this follows SOLID more ?

2023-07-24 15:45 UTC, vincecloutier approved these changes

2023-07-24 16:50 UTC, chelkisea approved these changes

2023-07-24 16:50 UTC, chelkisea commented on src/main/java/leaveRoom/LeaveRoomInputBoundary.java
> +    void leaveRoom(String roomId, String currUserId);
see note from LeaveRoomController

2023-07-24 16:50 UTC, chelkisea commented on src/main/java/leaveRoom/LeaveRoomInteractor.java
> +    public void leaveRoom(String roomId, String currUserId) {
see note from LeaveRoomController

2023-07-24 16:50 UTC, chelkisea commented on src/main/java/leaveRoom/RoomDBGateway.java
> +    void leaveRoom(String roomId, String currUserId);
see note from LeaveRoomController

2023-07-24 17:01 UTC, merged

2023-07-25 07:00 UTC, margaretpell commented on src/main/java/leaveRoom/RoomDBAccess.java
> +    }
changed it in 595b595

2023-07-25 07:00 UTC, margaretpell commented on src/main/java/leaveRoom/RoomDBRequestModel.java
> +    private String roomId;
changed it in 595b595

2023-07-25 07:00 UTC, margaretpell commented on src/main/java/leaveRoom/LeaveRoomController.java
> +package leaveRoom;
changed it in 595b595

2023-07-25 07:01 UTC, margaretpell commented on src/main/java/leaveRoom/LeaveRoomInteractor.java
> +                List<String> activeUsers = room.getActiveUsers();
I think it is right in the newest version. I can fix it if have any other problems later